version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: Download dependencies
          command: npm ci
#      - run:
#          name: Run build
#          command: npm run build
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Check dist folder
          command: |
            npm run build
            if git diff --quiet --exit-code ./dist ;
            then
              echo "Error: build is not up-to-date"
              exit 1
            fi
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
